### ISSUE TITLE
Extraneous garbage appended to data.

### ISSUE THREAD

**Issue by pmatts** [lclevy/firepwd#1]
While I'm happy that it kind of works, I would like to remove the extraneous garbage output e.g:

https://accounts.google.com: 'jon@mydomain.de\x02\x02' , 'mysecretphrase\x07\x07\x07\x07\x07\x07\x07'

How can I remove this
\x02\x02
\x07\x07\x07\x07\x07\x07\x07

Thankyou for the software.
Regards

**Comment by lclevy** [comment]
hi pmatts,
this is not garbage, this is PKCS#7 padding (see comment in the code source).
https://en.wikipedia.org/wiki/Padding_(cryptography)#PKCS7
to remove it, count how many identical values you have, starting from the end.
yep, you have 7 times \x07, and 2 times \x02
Regards,

**Comment by lclevy** [comment]
Lazagne tool, which use my code does this way
https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/browsers/mozilla.py#L463
I would add a verification that there is n times value n
