### ISSUE TITLE
New FF version changes its password implementation

### ISSUE THREAD

**Issue by AlessandroZ** [lclevy/firepwd#13]
Hi @lclevy, 

Hope you're doing well. 

They point me out that firefox implementation has change its way to store passwords: 
- https://github.com/AlessandroZ/LaZagne/issues/491
- https://github.com/louisabraham/ffpass/issues/49#issuecomment-586023952

If you have some time to take a look on it, it will be great (no rush). Thanks again for all your help. 

Have a nice day.

**Comment by lclevy** [comment]
Solved

**Comment by lclevy** [comment]
Solved
