### ISSUE TITLE
sqlite3.OperationalError: no such table: moz_logins

### ISSUE THREAD

**Issue by Papotito123** [lclevy/firepwd#14]
Hello;
Win 10 1809 x64.
Pyhton 3.7.16 x64.
Firefox 75 updated with 1 old saved password.

After some trial and error I got error but more pertinent than the fist ones I encountered.

There's no key3.db file in none of both Firefox profiles folders:
azatv8ct.default-release   <== these has up-to-date- files
ylho7ovy.default  <== here key4.db and signons.sqlite are zero kb

So I have to use this format to get it run"

C:\firepwd-master>python ".\firepwd.py" -d "C:\Users\TESTACCOUNT\AppData\Roaming\Mozilla\Firefox\Profiles\azatv8ct.default-release\\"

globalSalt: b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
 SEQUENCE {
   SEQUENCE {
     OBJECTIDENTIFIER 1.2.840.113549.1.12.5.1.3 pbeWithSha1AndTripleDES-CBC
     SEQUENCE {
       OCTETSTRING b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
       INTEGER b'01'
     }
   }
   OCTETSTRING b'axxxxxxxxxxxxxxxxxxxxxxxx'
 }
entrySalt: b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
password check? True
 SEQUENCE {
   SEQUENCE {
     OBJECTIDENTIFIER 1.2.840.113549.1.12.5.1.3 pbeWithSha1AndTripleDES-CBC
     SEQUENCE {
       OCTETSTRING b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
       INTEGER b'01'
     }
   }
   OCTETSTRING b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
 }
entrySalt: b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File ".\firepwd.py", line 403, in <module>
    logins = getLoginData()
  File ".\firepwd.py", line 195, in getLoginData
    c.execute("SELECT * FROM moz_logins;")
sqlite3.OperationalError: no such table: moz_logins
 

# requirements.txt typo:
Gives error for :  pyasn>=0.4.8
I changed to : pyasn1>=0.4.8  , and run requirements.txt well.

Any info much appreciated.

**Comment by lclevy** [comment]
Thanks for the asn1 typo. You need a valid json file and provide a password

**Comment by Papotito123** [comment]
Hello:
The logins.json file has info and username and password shows in encrypted form like base64.
I don't have set a Masterpassword.
But I read that can be used an empty password.
I can retrieve Firefox 75 login in a first-time installation with a tool.

Thanks for responding.

**Comment by Papotito123** [comment]
Hello:
Always gives error;
    c.execute("SELECT * FROM moz_logins;")
    sqlite3.OperationalError: no such table: moz_logins

while using firefox profile path as this:
C:\Users\TESTACCOUNT\AppData\Roaming\Mozilla\Firefox\Profiles\azatv8ct.default-release 

So I copied json.logins and key4.db from azatv8ct.default-release to C:\firepwd-master.
Then ran:
       C:\firepwd-master>firepwd.py -d "C:\firepwd-master\\"

,and got this;
globalSalt: b'salt'
 SEQUENCE {
   SEQUENCE {
     OBJECTIDENTIFIER 1.2.840.113549.1.12.5.1.3 pbeWithSha1AndTripleDES-CBC
     SEQUENCE {
       OCTETSTRING b'octetstring'
       INTEGER b'01'
     }
   }
   OCTETSTRING b'octectstring'
 }
entrySalt: b'entrySalt'
b'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
password check? True
 SEQUENCE {
   SEQUENCE {
     OBJECTIDENTIFIER 1.2.840.113549.1.12.5.1.3 pbeWithSha1AndTripleDES-CBC
     SEQUENCE {
       OCTETSTRING b'octetstring'
       INTEGER b'01'
     }
   }
   OCTETSTRING b'octeystring'
 }
entrySalt: b'entrySalt'
b'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'
decrypting login/password pairs
https://login.live.com:b'myemail@hotmail.com\x08\x08\x08\x08\x08\x08\x08\x08',b'mypassword\x03\x03\x03'

So ,there's the way should be output?
Any info much appreciated.
  
I see you improve your Readme and requirements.

Thanks.

**Comment by Papotito123** [comment]
Hello:
With respect and with my little knowledge,I think the problem when using  a profile full path is here:

def getLoginData(self, profile):
  logins = []
  sqlite_file = options.directory+'signons.sqlite' #firefox < 32
  if path.exists(sqlite_file):
    conn = sqlite3.connect(sqlite_file)
    c = conn.cursor()
    c.execute('SELECT * FROM moz_logins;')

signons.sqlite file exists in FF 75 , so at first see file and will runn this module that sI think should be for FF 32 or less.
When copying json.logins and key4.db top another place, of course , will not have to decide because there's no signons.sqlite file.
So ,can continue to run  ,else: #since Firefox 32, json is used instead of sqlite3  , that ia pertinent to FF75.

I'm not,coder/dev/IT.
I tried to change the order of the blocks but didn't sucess.

For me there's no problem testing any mod you want.

That's my honest appreciation.

Thanks.

**Comment by Papotito123** [comment]
Hello:
I mod the firepwd.py:

    return asn1data[0][0].asOctets(),  ............................................

def getLoginData():
  logins = []
  loginf = open(options.directory+'logins.json','r').read() 
  jsonLogins = json.loads(loginf)
  if path.exists(options.directory+'logins.json'):
    if 'logins' not in jsonLogins:
      print ('error: no \'logins\' key in logins.json')
      return []
    for row in jsonLogins['logins']:
      encUsername = row['encryptedUsername']
      encPassword = row['encryptedPassword']
      logins.append( (decodeLoginData(encUsername), decodeLoginData(encPassword), row['hostname']) )
    return logins

  else: 
    sqlite_file = open(options.directory+'signons.sqlite','r').read() 
    if path.exists(sqlite_file):
      conn = sqlite3.connect(sqlite_file)
      c = conn.cursor()
      c.execute("SELECT * FROM moz_logins;")
      for row in c:
        encUsername = row[6]
        encPassword = row[7]
        if options.verbose>1:
          print (row[1], encUsername, encPassword)
        logins.append( (decodeLoginData(encUsername), decodeLoginData(encPassword), row[1]) )
      return logins

def extractSecretKey(masterPassword, keyData): #3DES

It grabs the FF 75 logins without having to rename signons.sqlite.

If you can test it in  an old Firefox and for compatibility.
Maybe there's some redundance in the mod lines , but they workrd for me.

Thanks.
