### ISSUE TITLE
firepwd choose signons.sqlite instead logins.json

### ISSUE THREAD

**Issue by Papotito123** [lclevy/firepwd#15]
Hello:
With respect and with my little knowledge,I think the problem when using a profile full path, is here:

def getLoginData(self, profile):
logins = []
sqlite_file = options.directory+'signons.sqlite' #firefox < 32
if path.exists(sqlite_file):
conn = sqlite3.connect(sqlite_file)
c = conn.cursor()
c.execute('SELECT * FROM moz_logins;')

signons.sqlite file exists in FF 75 , so at first will seek this file and will run this module that should be for FF 32 or less not giving opportunity to seek and find for logins.json.
When copying json.logins and key4.db to another place, of course , will not have to decide because there's no signons.sqlite file.
So ,script can continue to run the module;
else: #since Firefox 32, json is used instead of sqlite3 

, that is pertinent to FF75.

** I changed signons.sqlite to signons.sqlite.bak, and firepwd.exe runs well. **

I'm not,coder/dev/IT.
That's my honest appreciation.

Thanks.

**Comment by Papotito123** [comment]
Hello:
I mod the firepwd.py:

return asn1data[0][0].asOctets(),  ............................................
def getLoginData():
logins = []
loginf = open(options.directory+'logins.json','r').read()
jsonLogins = json.loads(loginf)
if path.exists(options.directory+'logins.json'):
if 'logins' not in jsonLogins:
print ('error: no 'logins' key in logins.json')
return []
for row in jsonLogins['logins']:
encUsername = row['encryptedUsername']
encPassword = row['encryptedPassword']
logins.append( (decodeLoginData(encUsername), decodeLoginData(encPassword), row['hostname']) )
return logins

else:
sqlite_file = open(options.directory+'signons.sqlite','r').read()
if path.exists(sqlite_file):
conn = sqlite3.connect(sqlite_file)
c = conn.cursor()
c.execute("SELECT * FROM moz_logins;")
for row in c:
encUsername = row[6]
encPassword = row[7]
if options.verbose>1:
print (row[1], encUsername, encPassword)
logins.append( (decodeLoginData(encUsername), decodeLoginData(encPassword), row[1]) )
return logins

def extractSecretKey(masterPassword, keyData): #3DES

It will seek first for logins.json instead signons.sqlite.
It grabs the FF 75 logins without having to rename signons.sqlite.

If you can test it in an old Firefox and for compatibility.
Maybe there's some redundance in the mod lines , but they workrd for me.

Update:
In the module:
if 'logins' not in jsonLogins:
print ('error: no 'logins' key in logins.json')
return []

,there's an error because I tested in FF75 without a login saved and the script gives error instead a msg of  no logins in logins.json .

I hope you have time to test it.

Thanks.

**Comment by lclevy** [comment]
Hi, you're right this is a bug when someone upgraded from firefox <32. I'll test first the presence or the more recent file, here logins.json, instead of signons.sqlite

**Comment by Papotito123** [comment]
Hello:
Thanks for keep in touch.

**Comment by Papotito123** [comment]
Hello:
When in profile doesn't exists a logins.json(no saved password), or logins.json is blank/empty this error occurred:

Traceback (most recent call last):
  File "C:\firepwd-master\firepwd.py", line 406, in <module>
    key, algo = getKey(  options.masterPassword.encode(), options.directory )
  File "C:\firepwd-master\firepwd.py", line 387, in getKey
    printASN1( a11, len(a11), 0)
  File "C:\firepwd-master\firepwd.py", line 63, in printASN1
    print ('  '*rl, asn1Types[ type ],end=' ')
KeyError: 197

**Comment by Papotito123** [comment]
Hello:
I  tested latest git code and works very good.

I tested in FF 75 with no saved passwords and FF 75 with saved 1 password and did well.
I tested toward other users accounts and did good.
Also tested in a VBOX Win 10 1809 x64 with a FF 75 first-time installation with 1 saved password and worked good.

Maybe this is an exceptional case,but when I encountered an error was in FF 75 upgraded with an empty(blank) logins.json file due to no password is saved :

Traceback (most recent call last):
  File "C:\firepwd-master\firepwd.py", line 409, in <module>
    key, algo = getKey(  options.masterPassword.encode(), options.directory )
  File "C:\firepwd-master\firepwd.py", line 389, in getKey
    assert a102 == CKA_ID
AssertionError

As in the other firepwd.py, is seeking to compare something inside logins.json but when is fully empty just get stuck.I encountered this error in the other script.
Maybe is an exceptional situation.

As side note, AVAST scan compiled firepwd.exe but did not deleted as found Safe.

So much thanks.

**Comment by lclevy** [comment]
Hi,
Thanks for testing.
If you remove the Cka id assert, what is happening ?

**Comment by Papotito123** [comment]
Hello:
This issue shows when logins.json exists but is completely in blank/empty with no char/letter/number at all.

I tested by commenting this lines:

1.   when doing   #assert a102 == CKA_ID   ;
Traceback (most recent call last):
  File "C:\firepwd-master\firepwd.py", line 409, in <module>
    key, algo = getKey(  options.masterPassword.encode(), options.directory )
  File "C:\firepwd-master\firepwd.py", line 390, in getKey
    printASN1( a11, len(a11), 0)
  File "C:\firepwd-master\firepwd.py", line 64, in printASN1
    print ('  '*rl, asn1Types[ type ],end=' ')
KeyError: 197

2.   when doing   #assert i[0][0] == CKA_ID   ;
Traceback (most recent call last):
  File "C:\firepwd-master\firepwd.py", line 409, in <module>
    key, algo = getKey(  options.masterPassword.encode(), options.directory )
  File "C:\firepwd-master\firepwd.py", line 389, in getKey
    assert a102 == CKA_ID
AssertionError


3. when doing     #14 assert a102 == CKA_ID    AND    #assert i[0][0] == CKA_ID   ;  
Traceback (most recent call last):
  File "C:\firepwd-master\firepwd.py", line 409, in <module>
    key, algo = getKey(  options.masterPassword.encode(), options.directory )
  File "C:\firepwd-master\firepwd.py", line 390, in getKey
    printASN1( a11, len(a11), 0)
  File "C:\firepwd-master\firepwd.py", line 64, in printASN1
    print ('  '*rl, asn1Types[ type ],end=' ')
KeyError: 197


Maybe this is a typo:
else: 
    print('missing logins.json ot signons.sqlite')

**Comment by Papotito123** [comment]
Hello:
Testing your latest git when logins.json exists but is completely in blank/empty with no char/letter/number at all.

Traceback (most recent call last):
  File "C:\firepwd-master_new\firepwd.py", line 419, in <module>
    key, algo = getKey(  options.masterPassword.encode(), options.directory )
  File "C:\firepwd-master_new\firepwd.py", line 396, in getKey
    assert a102 == CKA_ID
AssertionError

Thanks

**Comment by lclevy** [comment]
fixed

**Comment by Papotito123** [comment]
Hello:
Tested latest git with "no saved login/password" fix and works very well.

So much thanks.
