### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

### ISSUE THREAD

**Issue by jschueller** [lclevy/firepwd#18]
I have an error with key3/signon files in the current folder:
```
$ python firepwd.py
Traceback (most recent call last):
  File "/home/js/projects/firepwd/firepwd.py", line 421, in <module>
    key, algo = getKey(  options.masterPassword.encode(), options.directory )
  File "/home/js/projects/firepwd/firepwd.py", line 406, in getKey
    keyData = readBsddb(directory+'key3.db')
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'
```
Python is 3.9.1
it goes away if I write "keyData = readBsddb('key3.db')"

**Comment by lclevy** [comment]
Ok, thanks

**Comment by jschueller** [comment]
i did not see #17, it probably fixes this

**Comment by cookiengineer** [comment]
@lclevy yes, indeed, my pull request is the fix for that. With the previous migration to the path library, this line was left out and still uses the wrong operand for the path string. My PR was the simple fix for that.
