### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by doggodanubus** [lclevy/firepwd#19]
The pip command should be the at the top of the read me. This will not access logins.json and only clamors for the key*.db files.

I'm not sure I've gotten this to work since it became part of lazagnia. I've never gotten lazagnia to work. 

I think I keep coming back because it worked well that one time and has a cool name.

**Comment by lclevy** [comment]
Saying Hi would be nice.
This tool works stand alone.
What is Firefox version are you using?

**Comment by doggodanubus** [comment]
88.0.1 (64-bit)
Ok key4.db and logins.json need to be in the directory you run it from. You can't make it the script executable on my system it acts weird. You can't use python3 you have to use python even though they are the same thing. You have to use python firepwd.py --password=xyzzy, you cannot use -p

I'm surprised I got it to work. I gave up the last time and forgot about that.

firefox_decrypt works without my doing any other setup and queries for my password on command line. But it goes and gets the info from the firefox directory and it's output is horrible.  I'd prefer how firepwd does it.
https://github.com/unode/firefox_decrypt

Thanks, I'm satisfied I have it working. At some point I'll see if Lasagna can be made to work.
