### ISSUE TITLE
password check? False

### ISSUE THREAD

**Issue by hobik** [lclevy/firepwd#22]
Hello I forgot my master pasword and Im trying to find my master password from my profile folder. 

Im trying this code: `python firepwd.py -p 'MISC*' -d [MY_PROFILE_PATH]` on windows 10.
I have key4.db and logins.json
This gives me this result:
clearText b'---SOMETHING HERE ---'
password check? False

Why I getting this result how can I handle the my master password with your code.

**Comment by lclevy** [comment]
Use this instead: https://github.com/Banaanhangwagen/hashcat/commit/ee7d8ef0e72e62d77cc0fcc3719c759c447be757?s=09
