### ISSUE TITLE
Error decrypting credentials

### ISSUE THREAD

**Issue by AlessandroZ** [lclevy/firepwd#3]
Hi, 

Since my last Firefox update, it fails to decrypt Firefox passwords (version 58.0.2 (64-bit))

Here is the error: 
```
test:/tmp/firepwd$ python firepwd.py -d /home/test/.mozilla/firefox/qutmp8yy.default/
decrypting login/password pairs
https://wordpress.com:
Traceback (most recent call last):
  File "firepwd.py", line 252, in <module>
    print repr( DES3.new( key, DES3.MODE_CBC, iv).decrypt(ciphertext) ), ',',
  File "/home/test/.local/lib/python2.7/site-packages/Crypto/Cipher/DES3.py", line 174, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/home/test/.local/lib/python2.7/site-packages/Crypto/Cipher/__init__.py", line 55, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/home/test/.local/lib/python2.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 232, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/home/test/.local/lib/python2.7/site-packages/Crypto/Cipher/DES3.py", line 99, in _create_base_cipher
    key = adjust_key_parity(key_in)
  File "/home/test/.local/lib/python2.7/site-packages/Crypto/Cipher/DES3.py", line 79, in adjust_key_parity
    if len(key_in) not in key_size:
TypeError: object of type 'NoneType' has no len()

```
I think the pattern has changed because it fails [here](https://github.com/lclevy/firepwd/blob/master/firepwd.py#L201). 

If you could take a look it could be great. Thanks a lot.

**Comment by lclevy** [comment]
Likely because NSS is now using SQL :
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.35_release_notes

**Comment by lclevy** [comment]
yep, private key is stored now in key4.db, in sqllite3 format.
https://hg.mozilla.org/projects/nss/file/256ac50bbb6b/lib/softoken/sdb.c
have to understand "nssPrivate" table

**Comment by AlessandroZ** [comment]
Not an easy task, thanks for your work !

**Comment by lclevy** [comment]
solved, see https://twitter.com/lorenzo2472/status/965714528636948480
soon in my code

**Comment by AlessandroZ** [comment]
Awesome, that was fast ! Thanks a lot. 
Waiting to see your code :)

**Comment by AlessandroZ** [comment]
If you have time to publish your code, it will be great. Thanks a lot.

**Comment by lclevy** [comment]
Hi, I pushed the code for key4.dn support

**Comment by AlessandroZ** [comment]
Awesome work, thanks a lot :+1: 

I have [pushed](https://github.com/AlessandroZ/LaZagne/blob/master/CHANGELOG#L9) your new code into my repo. Thanks again
