### ISSUE TITLE
UnboundLocalError: local variable 'key' referenced before assignment

### ISSUE THREAD

**Issue by ashwinik-mdn** [lclevy/firepwd#5]
Hi,
 I receive this error if use following command with firefox password store files in mozill_db/ folder.

C:\Users\Ashwini\Downloads\firepwd-master>python firepwd.py -p 'MISC*' -d mozilla_db/
 SEQUENCE {
   SEQUENCE {
     OBJECTIDENTIFIER 1.2.840.113549.1.12.5.1.3
     SEQUENCE {
       OCTETSTRING 1df64af83c0f3b9f518236de7486cea09f0bee1c
       INTEGER 01
     }
   }
   OCTETSTRING abab8fbfac3205b93f1a7e306e414aa7
 }
password check? False
Traceback (most recent call last):
  File "firepwd.py", line 297, in <module>
    key = getKey()
  File "firepwd.py", line 289, in getKey
    return key[:24]
UnboundLocalError: local variable 'key' referenced before assignment

Why do I get this error?

**Comment by lclevy** [comment]
It seems the password given in argument 'MISC*' is incorrect

**Comment by lclevy** [comment]
Is your data protected by a master password ?

**Comment by ashwinik-mdn** [comment]
Data is not protected by master password.

**Comment by ashwinik-mdn** [comment]
It is working. Thank you.
